/**
 * 12 public Singapore recipes. Ingredient `name` values reference canonical
 * ingredients from ingredients.ts so seeding links them directly.
 */

export interface SeedRecipeIngredient {
  name: string; // canonical ingredient name
  rawText: string;
  quantity: number;
  unit: string;
  grams: number; // normalized canonical grams
  optional?: boolean;
}

export interface SeedRecipe {
  title: string;
  description: string;
  servings: number;
  prepMinutes: number;
  cookMinutes: number;
  cuisine: string;
  tags: string[];
  instructions: string[];
  ingredients: SeedRecipeIngredient[];
}

export const SEED_RECIPES: SeedRecipe[] = [
  {
    title: 'Hainanese Chicken Rice',
    description: 'The national favourite — poached chicken, fragrant rice and ginger-chilli dips.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 50,
    cuisine: 'Singaporean',
    tags: ['hawker classic', 'chicken', 'rice'],
    instructions: [
      'Rub the chicken with salt, rinse, and stuff with ginger slices and spring onion.',
      'Poach the chicken in gently simmering water for 35–40 minutes, then plunge into iced water.',
      'Sauté garlic and ginger in chicken fat, add rice and cook with the poaching stock.',
      'Blend chilli, ginger, garlic and lime into the dipping sauces.',
      'Slice the chicken, drizzle with light soy and sesame oil, serve with rice and cucumber.',
    ],
    ingredients: [
      { name: 'whole chicken', rawText: '1 whole chicken (about 1.4 kg)', quantity: 1, unit: 'piece', grams: 1400 },
      { name: 'jasmine rice', rawText: '2 cups jasmine rice', quantity: 2, unit: 'cup', grams: 400 },
      { name: 'ginger', rawText: '60 g ginger, sliced', quantity: 60, unit: 'g', grams: 60 },
      { name: 'garlic', rawText: '6 cloves garlic', quantity: 6, unit: 'clove', grams: 30 },
      { name: 'spring onion', rawText: '3 stalks spring onion', quantity: 3, unit: 'stalk', grams: 45 },
      { name: 'cucumber', rawText: '1 cucumber, sliced', quantity: 1, unit: 'piece', grams: 300 },
      { name: 'red chilli', rawText: '4 red chillies for the sauce', quantity: 4, unit: 'piece', grams: 40 },
      { name: 'lime', rawText: '1 lime, juiced', quantity: 1, unit: 'piece', grams: 60 },
      { name: 'light soy sauce', rawText: '2 tbsp light soy sauce', quantity: 2, unit: 'tbsp', grams: 36 },
      { name: 'sesame oil', rawText: '1 tbsp sesame oil', quantity: 1, unit: 'tbsp', grams: 14 },
      { name: 'salt', rawText: '1 tbsp salt', quantity: 1, unit: 'tbsp', grams: 18 },
    ],
  },
  {
    title: 'Char Kway Teow',
    description: 'Smoky wok-fried flat rice noodles with lap cheong, egg and bean sprouts.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Singaporean',
    tags: ['hawker classic', 'noodles', 'wok'],
    instructions: [
      'Heat a wok until smoking, add oil and fry garlic until golden.',
      'Add prawns and fish cake, stir-fry 1 minute.',
      'Add kway teow and yellow noodles, then dark and light soy. Toss on high heat.',
      'Push aside, crack in eggs, scramble, then fold through with bean sprouts.',
      'Finish with chives and a squeeze of lime.',
    ],
    ingredients: [
      { name: 'kway teow', rawText: '400 g kway teow', quantity: 400, unit: 'g', grams: 400 },
      { name: 'yellow noodles', rawText: '150 g yellow noodles', quantity: 150, unit: 'g', grams: 150 },
      { name: 'prawns', rawText: '150 g prawns, peeled', quantity: 150, unit: 'g', grams: 150 },
      { name: 'fish cake', rawText: '100 g fish cake, sliced', quantity: 100, unit: 'g', grams: 100 },
      { name: 'eggs', rawText: '2 eggs', quantity: 2, unit: 'piece', grams: 110 },
      { name: 'bean sprouts', rawText: '150 g bean sprouts', quantity: 150, unit: 'g', grams: 150 },
      { name: 'garlic', rawText: '3 cloves garlic, minced', quantity: 3, unit: 'clove', grams: 15 },
      { name: 'dark soy sauce', rawText: '1.5 tbsp dark soy sauce', quantity: 1.5, unit: 'tbsp', grams: 27 },
      { name: 'light soy sauce', rawText: '1 tbsp light soy sauce', quantity: 1, unit: 'tbsp', grams: 18 },
      { name: 'vegetable oil', rawText: '3 tbsp oil', quantity: 3, unit: 'tbsp', grams: 41 },
      { name: 'sambal chilli', rawText: '1 tbsp sambal (optional)', quantity: 1, unit: 'tbsp', grams: 18, optional: true },
    ],
  },
  {
    title: 'Laksa Lemak',
    description: 'Rich coconut curry noodle soup with prawns, fish cake and tau pok.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 25,
    cuisine: 'Peranakan',
    tags: ['noodles', 'spicy', 'soup'],
    instructions: [
      'Fry laksa paste in oil until fragrant and split.',
      'Add coconut milk and 800 ml water, simmer 10 minutes.',
      'Blanch bee hoon and bean sprouts; halve the tau pok.',
      'Poach prawns and fish cake slices in the broth.',
      'Assemble bowls and ladle over the laksa gravy; garnish with laksa leaves.',
    ],
    ingredients: [
      { name: 'laksa paste', rawText: '180 g laksa paste', quantity: 180, unit: 'g', grams: 180 },
      { name: 'coconut milk', rawText: '400 ml coconut milk', quantity: 400, unit: 'ml', grams: 400 },
      { name: 'bee hoon', rawText: '300 g thick bee hoon', quantity: 300, unit: 'g', grams: 300 },
      { name: 'prawns', rawText: '300 g prawns', quantity: 300, unit: 'g', grams: 300 },
      { name: 'fish cake', rawText: '150 g fish cake', quantity: 150, unit: 'g', grams: 150 },
      { name: 'tau pok', rawText: '6 pieces tau pok', quantity: 6, unit: 'piece', grams: 90 },
      { name: 'bean sprouts', rawText: '150 g bean sprouts', quantity: 150, unit: 'g', grams: 150 },
      { name: 'eggs', rawText: '2 hard-boiled eggs, halved', quantity: 2, unit: 'piece', grams: 110 },
      { name: 'vegetable oil', rawText: '2 tbsp oil', quantity: 2, unit: 'tbsp', grams: 27 },
    ],
  },
  {
    title: 'Sambal Kangkong',
    description: 'Wok-charred water spinach in punchy belacan sambal — done in five minutes.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 5,
    cuisine: 'Singaporean',
    tags: ['vegetables', 'spicy', 'quick'],
    instructions: [
      'Pound or blitz chillies, garlic, shallots and belacan into a rough paste.',
      'Fry the paste in hot oil until fragrant.',
      'Add kangkong and toss on the highest heat for 2 minutes.',
      'Season with a splash of fish sauce and serve immediately.',
    ],
    ingredients: [
      { name: 'kangkong', rawText: '400 g kangkong, washed', quantity: 400, unit: 'g', grams: 400 },
      { name: 'red chilli', rawText: '3 red chillies', quantity: 3, unit: 'piece', grams: 30 },
      { name: 'garlic', rawText: '3 cloves garlic', quantity: 3, unit: 'clove', grams: 15 },
      { name: 'red onion', rawText: '2 small red onions', quantity: 2, unit: 'piece', grams: 120 },
      { name: 'belacan', rawText: '1 tsp belacan, toasted', quantity: 1, unit: 'tsp', grams: 6 },
      { name: 'fish sauce', rawText: '1 tsp fish sauce', quantity: 1, unit: 'tsp', grams: 6 },
      { name: 'vegetable oil', rawText: '2 tbsp oil', quantity: 2, unit: 'tbsp', grams: 27 },
    ],
  },
  {
    title: 'Singapore Chicken Curry',
    description: 'Comforting curry with potatoes and coconut milk — perfect with baguette or rice.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 45,
    cuisine: 'Singaporean',
    tags: ['chicken', 'curry', 'one-pot'],
    instructions: [
      'Marinate chicken pieces in curry powder for 15 minutes.',
      'Fry onion, garlic, ginger and curry leaves until fragrant.',
      'Brown the chicken, add potatoes and water; simmer 25 minutes.',
      'Stir in coconut milk and simmer gently 10 more minutes.',
      'Rest 10 minutes before serving — the curry thickens as it sits.',
    ],
    ingredients: [
      { name: 'chicken thigh', rawText: '800 g chicken thigh, bone-in', quantity: 800, unit: 'g', grams: 800 },
      { name: 'potato', rawText: '3 potatoes, quartered', quantity: 3, unit: 'piece', grams: 510 },
      { name: 'curry powder', rawText: '4 tbsp meat curry powder', quantity: 4, unit: 'tbsp', grams: 28 },
      { name: 'coconut milk', rawText: '250 ml coconut milk', quantity: 250, unit: 'ml', grams: 250 },
      { name: 'yellow onion', rawText: '1 large onion, sliced', quantity: 1, unit: 'piece', grams: 110 },
      { name: 'garlic', rawText: '4 cloves garlic', quantity: 4, unit: 'clove', grams: 20 },
      { name: 'ginger', rawText: '30 g ginger', quantity: 30, unit: 'g', grams: 30 },
      { name: 'curry leaves', rawText: '2 sprigs curry leaves', quantity: 2, unit: 'sprig', grams: 4 },
      { name: 'vegetable oil', rawText: '3 tbsp oil', quantity: 3, unit: 'tbsp', grams: 41 },
      { name: 'salt', rawText: '1 tsp salt', quantity: 1, unit: 'tsp', grams: 6 },
    ],
  },
  {
    title: 'ABC Soup',
    description: 'The gentle everyday soup of pork ribs, potato, carrot, corn and tomato.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 60,
    cuisine: 'Chinese',
    tags: ['soup', 'family', 'healthy'],
    instructions: [
      'Blanch pork ribs in boiling water for 3 minutes, rinse.',
      'Add ribs and 1.8 L water to a pot, simmer 30 minutes.',
      'Add potato, carrot, corn and onion; simmer 25 minutes.',
      'Add tomato wedges for the final 5 minutes and season with salt and white pepper.',
    ],
    ingredients: [
      { name: 'pork ribs', rawText: '500 g pork ribs', quantity: 500, unit: 'g', grams: 500 },
      { name: 'potato', rawText: '2 potatoes', quantity: 2, unit: 'piece', grams: 340 },
      { name: 'carrot', rawText: '2 carrots', quantity: 2, unit: 'piece', grams: 120 },
      { name: 'sweet corn', rawText: '1 sweet corn, cut into rounds', quantity: 1, unit: 'piece', grams: 250 },
      { name: 'tomato', rawText: '2 tomatoes, wedged', quantity: 2, unit: 'piece', grams: 240 },
      { name: 'yellow onion', rawText: '1 onion', quantity: 1, unit: 'piece', grams: 110 },
      { name: 'white pepper', rawText: '1/2 tsp white pepper', quantity: 0.5, unit: 'tsp', grams: 1.5 },
      { name: 'salt', rawText: '1 tsp salt', quantity: 1, unit: 'tsp', grams: 6 },
    ],
  },
  {
    title: 'Egg Fried Rice',
    description: 'Day-old rice, eggs and spring onion — the fastest dinner there is.',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 8,
    cuisine: 'Chinese',
    tags: ['rice', 'quick', 'budget'],
    instructions: [
      'Beat the eggs with a pinch of salt.',
      'Scramble eggs in hot oil, remove at 70% cooked.',
      'Fry garlic, add rice and break up the clumps on high heat.',
      'Return eggs, season with light soy and white pepper, toss through spring onion and peas.',
    ],
    ingredients: [
      { name: 'jasmine rice', rawText: '300 g cooked jasmine rice (day-old)', quantity: 300, unit: 'g', grams: 300 },
      { name: 'eggs', rawText: '3 eggs', quantity: 3, unit: 'piece', grams: 165 },
      { name: 'frozen peas', rawText: '80 g frozen peas', quantity: 80, unit: 'g', grams: 80 },
      { name: 'spring onion', rawText: '2 stalks spring onion', quantity: 2, unit: 'stalk', grams: 30 },
      { name: 'garlic', rawText: '2 cloves garlic', quantity: 2, unit: 'clove', grams: 10 },
      { name: 'light soy sauce', rawText: '1 tbsp light soy sauce', quantity: 1, unit: 'tbsp', grams: 18 },
      { name: 'white pepper', rawText: '1/4 tsp white pepper', quantity: 0.25, unit: 'tsp', grams: 0.8 },
      { name: 'vegetable oil', rawText: '2 tbsp oil', quantity: 2, unit: 'tbsp', grams: 27 },
    ],
  },
  {
    title: 'Mee Goreng Mamak',
    description: 'Sweet-spicy fried yellow noodles with tofu, potato and egg.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 10,
    cuisine: 'Indian-Muslim',
    tags: ['noodles', 'spicy', 'hawker classic'],
    instructions: [
      'Fry onion and garlic, add diced boiled potato and firm tofu.',
      'Add noodles, kecap manis, chilli sauce and tomato ketchup; toss well.',
      'Push aside, scramble the egg, then fold everything together.',
      'Finish with bean sprouts and a lime wedge.',
    ],
    ingredients: [
      { name: 'yellow noodles', rawText: '400 g yellow noodles', quantity: 400, unit: 'g', grams: 400 },
      { name: 'firm tofu', rawText: '150 g firm tofu, cubed', quantity: 150, unit: 'g', grams: 150 },
      { name: 'potato', rawText: '1 boiled potato, diced', quantity: 1, unit: 'piece', grams: 170 },
      { name: 'eggs', rawText: '2 eggs', quantity: 2, unit: 'piece', grams: 110 },
      { name: 'bean sprouts', rawText: '100 g bean sprouts', quantity: 100, unit: 'g', grams: 100 },
      { name: 'yellow onion', rawText: '1 onion, sliced', quantity: 1, unit: 'piece', grams: 110 },
      { name: 'garlic', rawText: '3 cloves garlic', quantity: 3, unit: 'clove', grams: 15 },
      { name: 'kecap manis', rawText: '2 tbsp kecap manis', quantity: 2, unit: 'tbsp', grams: 36 },
      { name: 'chilli sauce', rawText: '2 tbsp chilli sauce', quantity: 2, unit: 'tbsp', grams: 36 },
      { name: 'tomato ketchup', rawText: '1 tbsp ketchup', quantity: 1, unit: 'tbsp', grams: 18 },
      { name: 'lime', rawText: '1 lime, wedged', quantity: 1, unit: 'piece', grams: 60 },
      { name: 'vegetable oil', rawText: '2 tbsp oil', quantity: 2, unit: 'tbsp', grams: 27 },
    ],
  },
  {
    title: 'Teochew Steamed Fish',
    description: 'Clean, bright steamed sea bass with tomato, tofu and preserved flavours.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 12,
    cuisine: 'Teochew',
    tags: ['seafood', 'healthy', 'steamed'],
    instructions: [
      'Score the fish and lay on a heatproof plate with tomato wedges and silken tofu.',
      'Top with ginger strips and a drizzle of light soy.',
      'Steam over high heat 10–12 minutes until just cooked.',
      'Garnish with spring onion and coriander; spoon over the steaming juices.',
    ],
    ingredients: [
      { name: 'sea bass', rawText: '1 whole sea bass (about 600 g)', quantity: 1, unit: 'piece', grams: 600 },
      { name: 'silken tofu', rawText: '200 g silken tofu, sliced', quantity: 200, unit: 'g', grams: 200 },
      { name: 'tomato', rawText: '1 tomato, wedged', quantity: 1, unit: 'piece', grams: 120 },
      { name: 'ginger', rawText: '20 g ginger, julienned', quantity: 20, unit: 'g', grams: 20 },
      { name: 'spring onion', rawText: '2 stalks spring onion', quantity: 2, unit: 'stalk', grams: 30 },
      { name: 'coriander', rawText: 'small bunch coriander', quantity: 1, unit: 'bunch', grams: 25 },
      { name: 'light soy sauce', rawText: '2 tbsp light soy sauce', quantity: 2, unit: 'tbsp', grams: 36 },
      { name: 'sesame oil', rawText: '1 tsp sesame oil', quantity: 1, unit: 'tsp', grams: 5 },
    ],
  },
  {
    title: 'Claypot Chicken Rice',
    description: 'One-pot rice with marinated chicken, mushrooms and a dark-soy crust.',
    servings: 3,
    prepMinutes: 20,
    cookMinutes: 35,
    cuisine: 'Cantonese',
    tags: ['rice', 'one-pot', 'chicken'],
    instructions: [
      'Marinate chicken in oyster sauce, light soy, sesame oil and white pepper.',
      'Par-cook rice in the claypot for 10 minutes.',
      'Nestle chicken and mushrooms on top; cook covered 15 minutes.',
      'Drizzle dark soy, scatter spring onion, and crisp the base 3 minutes before serving.',
    ],
    ingredients: [
      { name: 'chicken thigh', rawText: '500 g boneless chicken thigh', quantity: 500, unit: 'g', grams: 500 },
      { name: 'jasmine rice', rawText: '1.5 cups jasmine rice', quantity: 1.5, unit: 'cup', grams: 300 },
      { name: 'shiitake mushroom', rawText: '6 fresh shiitake, sliced', quantity: 6, unit: 'piece', grams: 120 },
      { name: 'oyster sauce', rawText: '2 tbsp oyster sauce', quantity: 2, unit: 'tbsp', grams: 36 },
      { name: 'light soy sauce', rawText: '1 tbsp light soy sauce', quantity: 1, unit: 'tbsp', grams: 18 },
      { name: 'dark soy sauce', rawText: '1 tbsp dark soy sauce', quantity: 1, unit: 'tbsp', grams: 18 },
      { name: 'sesame oil', rawText: '1 tbsp sesame oil', quantity: 1, unit: 'tbsp', grams: 14 },
      { name: 'ginger', rawText: '20 g ginger, sliced', quantity: 20, unit: 'g', grams: 20 },
      { name: 'spring onion', rawText: '2 stalks spring onion', quantity: 2, unit: 'stalk', grams: 30 },
      { name: 'white pepper', rawText: '1/2 tsp white pepper', quantity: 0.5, unit: 'tsp', grams: 1.5 },
    ],
  },
  {
    title: 'Tofu & Broccoli Stir-fry',
    description: 'Weeknight vegetarian stir-fry in a garlicky oyster-style sauce.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
    cuisine: 'Chinese',
    tags: ['vegetarian', 'healthy', 'quick'],
    instructions: [
      'Pan-fry tofu cubes until golden on all sides; set aside.',
      'Blanch broccoli florets 1 minute.',
      'Fry garlic, add broccoli and carrot, then the sauce (oyster sauce, soy, corn flour slurry).',
      'Return tofu, toss to coat, finish with sesame oil.',
    ],
    ingredients: [
      { name: 'firm tofu', rawText: '300 g firm tofu, cubed', quantity: 300, unit: 'g', grams: 300 },
      { name: 'broccoli', rawText: '1 head broccoli', quantity: 1, unit: 'head', grams: 350 },
      { name: 'carrot', rawText: '1 carrot, sliced', quantity: 1, unit: 'piece', grams: 60 },
      { name: 'garlic', rawText: '3 cloves garlic', quantity: 3, unit: 'clove', grams: 15 },
      { name: 'oyster sauce', rawText: '2 tbsp oyster sauce', quantity: 2, unit: 'tbsp', grams: 36 },
      { name: 'light soy sauce', rawText: '1 tbsp light soy sauce', quantity: 1, unit: 'tbsp', grams: 18 },
      { name: 'corn flour', rawText: '1 tsp corn flour in 60 ml water', quantity: 1, unit: 'tsp', grams: 3 },
      { name: 'sesame oil', rawText: '1 tsp sesame oil', quantity: 1, unit: 'tsp', grams: 5 },
      { name: 'vegetable oil', rawText: '2 tbsp oil', quantity: 2, unit: 'tbsp', grams: 27 },
    ],
  },
  {
    title: 'Bak Chor Mee',
    description: 'Springy egg noodles tossed in vinegar-chilli sauce with minced pork and mushrooms.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 15,
    cuisine: 'Teochew',
    tags: ['noodles', 'hawker classic', 'pork'],
    instructions: [
      'Simmer sliced dried shiitake in a soy braise until tender.',
      'Season minced pork and blanch briefly in stock.',
      'Mix sambal, black vinegar, light soy and lard/oil in each bowl.',
      'Blanch noodles, toss in the sauce, top with pork, mushrooms and fish balls.',
    ],
    ingredients: [
      { name: 'egg noodles', rawText: '300 g thin egg noodles (mee kia)', quantity: 300, unit: 'g', grams: 300 },
      { name: 'minced pork', rawText: '250 g minced pork', quantity: 250, unit: 'g', grams: 250 },
      { name: 'dried shiitake', rawText: '6 dried shiitake, soaked & sliced', quantity: 6, unit: 'piece', grams: 30 },
      { name: 'fish ball', rawText: '6 fish balls', quantity: 6, unit: 'piece', grams: 120 },
      { name: 'black vinegar', rawText: '2 tbsp black vinegar', quantity: 2, unit: 'tbsp', grams: 30 },
      { name: 'sambal chilli', rawText: '2 tbsp sambal chilli', quantity: 2, unit: 'tbsp', grams: 36 },
      { name: 'light soy sauce', rawText: '1 tbsp light soy sauce', quantity: 1, unit: 'tbsp', grams: 18 },
      { name: 'vegetable oil', rawText: '1 tbsp oil', quantity: 1, unit: 'tbsp', grams: 14 },
      { name: 'spring onion', rawText: '1 stalk spring onion', quantity: 1, unit: 'stalk', grams: 15 },
    ],
  },
];
