apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-grocery
  annotations:
    alb.ingress.kubernetes.io/group.name: smart-grocery-staging
spec:
  rules:
    - host: staging.app.example.sg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: staging.api.example.sg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
